---
title: Guide pratique de la Sociocratie 3.0
email: bernhard.bockelbrink@gmail.com
description: >
  La description officielle de la Sociocratie 3.0 - Toutes les pratiques, les Sept Principes et les concepts clés. Préservé par Bernhard Bockelbrink, James Priest et Liliana David.
baseurl: ""
url: "http://s3-working-group.github.io"
twitter_username: sociocracy30
source: .
destination: ./_site
layouts_dir: ./_layouts
includes_dir: ./_includes
markdown: kramdown
safe: true
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
exclude:
  - _export
  - _python
  - _templates
